use_frameworks!

target 'AssemblyProjectDeamo_Example' do
  pod 'AssemblyProjectDeamo', :path => '../'

  target 'AssemblyProjectDeamo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
